name: SpikeBall
version: 0.1
author: Mathematician/ Kartik Dharmarajan
main: Mathematician.spikeball.SpikeBallMain
api-version: 1.15
commands:
  spikeball:
    description: This command is in charge of the Spike Ball System.
    usage: /<command> [player]
    permission: SpikeBall.spikeball
    permission-message: You don't have <permission>
