Spike Ball:
  Using Texture Pack: true
  Net Locations:
  - ==: org.bukkit.Location
    world: tps_world
    x: 255.0
    y: 117.0
    z: 529.0
    pitch: 0.0
    yaw: 0.0
  - ==: org.bukkit.Location
    world: tps_world
    x: 254.0
    y: 117.0
    z: 528.0
    pitch: 0.0
    yaw: 0.0
  - ==: org.bukkit.Location
    world: tps_world
    x: 265.0
    y: 116.0
    z: 514.0
    pitch: 0.0
    yaw: 0.0
